### ISSUE TITLE
Not working on colab / google cloud / aws

### ISSUE THREAD

**Issue by nselearner** [aeron7/nsepython#1]
Hi sir 
everything works fine on local pc but not working on any of cloud server VM
print(indices)
print(fnolist())
above two function works fine in cloud too..
print(nse_optionchain_scrapper('PVR')) is not woking ...

please resolve it ...
thank you

**Comment by nselearner** [comment]
`from nsepython import *
print(indices)
print(fnolist())
print(nse_optionchain_scrapper('PVR'))`

output

`['NIFTY', 'NIFTYIT', 'BANKNIFTY']
['BANKNIFTY', 'NIFTY', 'Symbol', 'BIOCON', 'CUMMINSIND', 'CADILAHC', 'HDFCBANK', 'INFY', 'LICHSGFIN', 'PVR', 'RAMCOCEM', 'ACC', 'ADANIENT', 'ADANIPORTS', 'AMARAJABAT', 'AMBUJACEM', 'APOLLOTYRE', 'ASHOKLEY', 'ASIANPAINT', 'AUROPHARMA', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE', 'BALKRISIND', 'BANDHANBNK', 'BANKBARODA', 'BATAINDIA', 'BEL', 'BERGEPAINT', 'BHARATFORG', 'BHARTIARTL', 'BHEL', 'BOSCHLTD', 'BPCL', 'BRITANNIA', 'CANBK', 'CENTURYTEX', 'CHOLAFIN', 'CIPLA', 'COALINDIA', 'INDUSINDBK', 'COLPAL', 'JUBLFOOD', 'CONCOR', 'DABUR', 'DIVISLAB', 'DLF', 'EICHERMOT', 'EQUITAS', 'ESCORTS', 'EXIDEIND', 'FEDERALBNK', 'GAIL', 'GODREJCP', 'GODREJPROP', 'GRASIM', 'HAVELLS', 'HCLTECH', 'HDFC', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDPETRO', 'HINDUNILVR', 'IBULHSGFIN', 'ICICIBANK', 'ICICIPRULI', 'IDFCFIRSTB', 'IGL', 'INDIGO', 'IOC', 'ITC', 'JINDALSTEL', 'JSWSTEEL', 'JUSTDIAL', 'KOTAKBANK', 'L&TFH', 'LT', 'M&M', 'M&MFIN', 'MANAPPURAM', 'MARUTI', 'MGL', 'MINDTREE', 'MOTHERSUMI', 'MRF', 'MUTHOOTFIN', 'NATIONALUM', 'NAUKRI', 'NCC', 'NESTLEIND', 'NMDC', 'NTPC', 'ONGC', 'PAGEIND', 'PEL', 'PETRONET', 'PFC', 'PIDILITIND', 'PNB', 'RBLBANK', 'RECLTD', 'DRREDDY', 'RELIANCE', 'SAIL', 'SBILIFE', 'SBIN', 'SHREECEM', 'SIEMENS', 'SRF', 'SRTRANSFIN', 'SUNPHARMA', 'TATACHEM', 'TATACONSUM', 'TATAMOTORS', 'GLENMARK', 'TATAPOWER', 'TATASTEEL', 'TCS', 'GMRINFRA', 'TECHM', 'TITAN', 'TORNTPHARM', 'TVSMOTOR', 'UBL', 'UJJIVAN', 'ULTRACEMCO', 'UPL', 'VEDL', 'VOLTAS', 'ZEEL', 'IDEA', 'LUPIN', 'MARICO', 'MCDOWELL-N', 'POWERGRID', 'WIPRO', 'INFRATEL', 'NIITTECH', 'TORNTPOWER', 'MFSL', 'SUNTV']
---------------------------------------------------------------------------
ConnectionResetError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

31 frames
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

ProtocolError                             Traceback (most recent call last)
ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    496 
    497         except (ProtocolError, socket.error) as err:
--> 498             raise ConnectionError(err, request=request)
    499 
    500         except MaxRetryError as e:

ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

**Comment by rajartp** [comment]
Yes. Its doesn't work in AWS cloud. I confirm it. Maybe NSE has blocked the IPs of AWS

**Comment by aeron7** [comment]
Refer https://aeron7.github.io/nsepython/documentation/#google-cloud-aws-servers
