### ISSUE TITLE
Future warning of frame append while using oi_chain_builder()

### ISSUE THREAD

**Issue by Dipak2022** [aeron7/nsepython#12]
Hi,
I am using oi_chain_builder(), But getting following warning.

rahu.py:146: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

I tried to modify line no. 146 of rahu.py:          oi_data = oi_data.append(oi_row, ignore_index=True)       as         oi_data = pd.concat([oi_data,oi_row],index=False), but not succeed.

Could anyone please guide me to get rid of this error.

**Comment by aeron7** [comment]
It is telling it will stop working in the future. That is not an error. I will change the code when it stops working. Till then don't try to extinguish the fire which has not been lit on.
