### ISSUE TITLE
How to use cURL command to retrieve data in AWS 

### ISSUE THREAD

**Issue by Arthavruksha** [aeron7/nsepython#13]
Hi so I am using Results Calendar function of this library and also read that I will have to use curl shell command to run code in Cloud

Can u provide me a road map or code of exactly how to run code using cURL command ??

Thanks

**Comment by aeron7** [comment]
https://stackoverflow.com/questions/59740840/why-my-program-to-scrape-nse-website-gets-blocked-in-servers-but-works-in-local/59794681?noredirect=1#comment125031323_59794681
