### ISSUE TITLE
Unable to get derivative history

### ISSUE THREAD

**Issue by reservoirinvest** [aeron7/nsepython#23]
Unable to get derivative history.    
The sample program in [documentation](https://unofficed.com/nse-python/documentation/nsepy/#derivative_history) also does not work.

```python
symbol = "SBIN"
start_date = "15-05-2021"
end_date ="15-06-2021"
instrumentType = "options"
expiry_date ="24-Jun-2021"
strikePrice = 300
optionType="PE"
print(derivative_history(symbol,start_date,end_date,instrumentType,expiry_date,strikePrice,optionType))
```

**Comment by aeron7** [comment]
Not providing support using GitHub Issues. Follow https://forum.unofficed.com/
