### ISSUE TITLE
Multi Request: 401

### ISSUE THREAD

**Issue by pars2721** [aeron7/nsepython#33]
Getting requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
due to Unauthorized 401 error resulting after Mimicking FrontPage visit.

Even after using the commit https://github.com/aeron7/nsepython/pull/31/commits/b0b7d360ce766bae68b758284807fcaee89446f6 was not able to resolve the issue

Have raised PR for tackling below issue https://github.com/aeron7/nsepython/pull/34/commits/70accbfc82e1d09d8ff3341c3aecdd84a7939b7a

The main use case is to iterate over all nse_eq symbols
```
symbols = nse_eq_symbols()
for symbol in symbols[:3]:
    print("This is my symbol :: ",symbol)
    df = nse_eq(symbol)
    print("Price info :: ",df['priceInfo'])
    open_val,high,low,current = df['priceInfo']['open'],df['priceInfo']['intraDayHighLow']['max'],df['priceInfo']['intraDayHighLow']['min'],df['priceInfo']['lastPrice']
    print("Open value :: ",open_val)
    print("High value :: ",high)
    print("Low value :: ",low)
    print("Current value :: ",current)

**Comment by aeron7** [comment]
https://forum.unofficed.com/t/nse-results-giving-jsondecodeerror/1315/7
