### ISSUE TITLE
Nsefetch function bug

### ISSUE THREAD

**Issue by ShardulPrabhu** [aeron7/nsepython#36]
<img width="1145" alt="image" src="https://github.com/aeron7/nsepython/assets/112759391/8693efdd-1772-4f37-8ec1-20028aaac226">

Hello Team,

Can you comment out print from local mode ? nsefetch fuction 

<img width="684" alt="image" src="https://github.com/aeron7/nsepython/assets/112759391/94f099c3-753f-453c-939d-8efd123cf704">

here

**Comment by aeron7** [comment]
Support and Beta Functions
If you have other doubts or want to check out the beta functions, visit the [NSEPython Discussions](https://forum.unofficed.com/c/programming/nse-python-api/) forum.
If you have feature requests, you can submit them at the [NSEPython Feature Request](https://forum.unofficed.com/t/nsepython-discussion-and-feature-request/665) forum.
