### ISSUE TITLE
nse data fetch issue

### ISSUE THREAD

**Issue by 000-arunkumar** [aeron7/nsepython#38]
**Issue:**
can't able to fetch index history using **index_history** function

**ERROR:**

"""
KeyError                                  Traceback (most recent call last)
[<ipython-input-5-423bdf98e849>](https://localhost:8080/#) in <cell line: 6>()
      4 start_date_r = start_date.strftime("%d-%b-%Y")
      5 print(end_date_r, start_date_r)
----> 6 df = index_history(symbol,start_date_r,end_date_r)
      7 len(df)

[/usr/local/lib/python3.10/dist-packages/nsepython/rahu.py](https://localhost:8080/#) in index_history(symbol, start_date, end_date)
    746     data = "{'name':'"+symbol+"','startDate':'"+start_date+"','endDate':'"+end_date+"'}"
    747     payload = requests.post('https://niftyindices.com/Backpage.aspx/getHistoricaldatatabletoString', headers=niftyindices_headers,  data=data).json()
--> 748     payload = json.loads(payload["d"])
    749     payload=pd.DataFrame.from_records(payload)
    750     return payload

KeyError: 'd'
"""

**note:**
payload = requests.post('https://niftyindices.com/Backpage.aspx/getHistoricaldatatabletoString', headers=niftyindices_headers,  data=data).json()

payload={'Message': 'There was an error processing the request.',
 'StackTrace': '',
 'ExceptionType': ''}

**Comment by andiamvinay** [comment]
I'm running into the same issue @aeron7

**Comment by supriyom083** [comment]
replace index_history function with below function body in rahu.py 

def index_history(symbol,start_date,end_date):
    data = {"name": symbol,
    "startDate": start_date,
    "endDate": end_date,
            }
    data={"cinfo":json.dumps(data)}    
    payload = requests.post('https://www.niftyindices.com/Backpage.aspx/getHistoricaldatatabletoString', timeout=300, headers=niftyindices_headers,  json=data,).json()
    
    payload = json.loads(payload["d"])
    payload=pd.DataFrame.from_records(payload)
    return payload

**Comment by 000-arunkumar** [comment]
> replace index_history function with below function body in rahu.py
> 
> def index_history(symbol,start_date,end_date): data = {"name": symbol, "startDate": start_date, "endDate": end_date, } data={"cinfo":json.dumps(data)} payload = requests.post('https://www.niftyindices.com/Backpage.aspx/getHistoricaldatatabletoString', timeout=300, headers=niftyindices_headers, json=data,).json() payload = json.loads(payload["d"]) payload=pd.DataFrame.from_records(payload) return payload

This is working. Thanks

**Comment by buzzvolt** [comment]
https://github.com/aeron7/nsepython/pull/40 will take care of this @aeron7

**Comment by aeron7** [comment]
Support and Beta Functions
If you have other doubts or want to check out the beta functions, visit the [NSEPython Discussions](https://forum.unofficed.com/c/programming/nse-python-api/) forum.
If you have feature requests, you can submit them at the [NSEPython Feature Request](https://forum.unofficed.com/t/nsepython-discussion-and-feature-request/665) forum.
