### ISSUE TITLE
is_market_open bug

### ISSUE THREAD

**Issue by ishankgoel** [aeron7/nsepython#39]
function is_market_open return true even if is holiday today. 
Problem is in the line: https://github.com/aeron7/nsepython/blob/6f3a7285d39e874d6b677df0286a966e1982e56f/nsepython/rahu.py#L909

This only checks for first holiday from the nse_holidays() json result and return True by checking only the first. It should be continue here to check for the next holiday date and a final return true at the end of function.

**Comment by aeron7** [comment]
Support and Beta Functions
If you have other doubts or want to check out the beta functions, visit the [NSEPython Discussions](https://forum.unofficed.com/c/programming/nse-python-api/) forum.
If you have feature requests, you can submit them at the [NSEPython Feature Request](https://forum.unofficed.com/t/nsepython-discussion-and-feature-request/665) forum.
