### ISSUE TITLE
equity_history has stopped working

### ISSUE THREAD

**Issue by pjsurve** [aeron7/nsepython#49]
Looks like this filter is not supported anymore
![image](https://github.com/user-attachments/assets/e05b6152-cb35-4bfb-be25-a8b45860a90c)

**Comment by akshay-bothra** [comment]
This seems to be an issue with the response text return by nse. The response json is not parsable.
![image](https://github.com/user-attachments/assets/cd801e25-41c8-4469-902e-9cdf585e555a)

**Comment by pjsurve** [comment]
Looks like you fixed it already it is working now.

**Comment by aeron7** [comment]
Use https://forum.unofficed.com/ to address.
