### ISSUE TITLE
Feature request to download individual Security Delivery details

### ISSUE THREAD

**Issue by SMVSKN** [aeron7/nsepython#52]
Hi,
Can a function to download the security delivery details be added. 

URL: https://www.nseindia.com/report-detail/eq_security

Eg: Ref URL: https://www.nseindia.com/api/historical/securityArchives?from=02-10-2024&to=02-11-2024&symbol=INFY&dataType=priceVolumeDeliverable&series=ALL&csv=true

**Comment by aeron7** [comment]
Use https://forum.unofficed.com/ to address.
